### ISSUE TITLE
axes tunes fail sometimes

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/ipython-usaxs#401] opened 2020-09-15 16:50 UTC
e-mail messages come with "tune ... failed" from BS. 
see tune_mr 'edae2b21", scan number 73
We get error reports: LivePlot did not get any data that corresponds to the x axis. m_stage_r. 
same message for axis y, I0_USAXS. 
This seems quite common today, have not seen any over night, but received at least 6 or more today morning.

**Comment by jilavsky** [comment] 2020-09-15 16:52
See tunebug.txt in CWD

**Comment by jilavsky** [comment] 2020-09-15 16:59
11:57 e-mail: USAXS tune failed for axis m_stage_r
11:58 e-mail: USAXS tune failed for axis a_stage_r
This is not very common occurrence, but scan data look OK.

**Comment by jilavsky** [comment] 2020-09-15 17:15
This is now getting critical, it is happening every time we tune the data.

**Comment by prjemian** [comment] 2020-09-15 17:33
might be a duplicate of #390

**Comment by prjemian** [comment] 2020-09-15 17:59
We did not understand these tunes should start failing since we are using the same session that ran almost 1k runs last night with no problem.  Instead, we exited the session, did a `git pull` on the instrument package, then restarted bluesky.

I suspect we created a problem sometime in our interactive session this morning and that caused the problem.

**Comment by prjemian** [comment] 2020-09-15 18:02
not a problem after we restarted

**Comment by prjemian** [comment] 2020-09-15 18:15
transient problem gone away after restart

**Closed by prjemian** 2020-09-15 18:15 UTC
Labels: bug

**Comment by prjemian** [comment] 2020-09-15 18:23
FWIW, here was the console output we observed with the problem.  Perfectly decent tune scan.  LivePlot could not find either of the plottable axes.  I do not see a column with the X axis (motor positions):

```
Transient Scan ID: 73     Time: 2020-09-15 11:46:09
Persistent Unique Scan ID: 'edae2b21-b91c-4c37-983b-6cce472df33c'
New stream: 'baseline'
New stream: 'aps_current_monitor'
New stream: 'primary'                                                                                                                                                         
+-----------+------------+------------+
|   seq_num |       time |   I0_USAXS |
+-----------+------------+------------+
|         1 | 11:46:10.8 |        541 |
|         2 | 11:46:11.2 |        752 |                                                                                                                                       
|         3 | 11:46:11.6 |       1216 |                                                                                                                                       
|         4 | 11:46:12.1 |       2145 |                                                                                                                                       
|         5 | 11:46:12.5 |       3851 |                                                                                                                                       
|         6 | 11:46:12.9 |       7005 |                                                                                                                                       
|         7 | 11:46:13.3 |      10687 |                                                                                                                                       
|         8 | 11:46:13.7 |      16346 |                                                                                                                                       
|         9 | 11:46:14.1 |      21881 |                                                                                                                                       
|        10 | 11:46:14.6 |      27599 |                                                                                                                                       
|        11 | 11:46:15.0 |      32012 |                                                                                                                                       
|        12 | 11:46:15.4 |      34801 |                                                                                                                                       
|        13 | 11:46:15.8 |      37044 |                                                                                                                                       
|        14 | 11:46:16.2 |      38260 |                                                                                                                                       
|        15 | 11:46:16.6 |      38882 |                                                                                                                                       
|        16 | 11:46:17.0 |      39157 |                                                                                                                                       
|        17 | 11:46:17.5 |      39397 |                                                                                                                                       
|        18 | 11:46:17.9 |      39391 |                                                                                                                                       
|        19 | 11:46:18.3 |      38617 |                                                                                                                                       
|        20 | 11:46:18.7 |      36936 |                                                                                                                                       
|        21 | 11:46:19.1 |      33898 |                                                                                                                                       
|        22 | 11:46:19.5 |      30408 |                                                                                                                                       
|        23 | 11:46:20.0 |      24834 |                                                                                                                                       
|        24 | 11:46:20.4 |      17924 |                                                                                                                                       
|        25 | 11:46:20.8 |      12196 |                                                                                                                                       
|        26 | 11:46:21.2 |       7266 |                                                                                                                                       
|        27 | 11:46:21.6 |       3918 |                                                                                                                                       
|        28 | 11:46:22.0 |       1997 |                                                                                                                                       
|        29 | 11:46:22.4 |       1076 |                                                                                                                                       
|        30 | 11:46:22.8 |        723 |                                                                                                                                       
|        31 | 11:46:23.3 |        528 |                                                                                                                                       
I Tue-11:46:23 - PeakStats : no max reported
+-----------+------------+------------+
generator tune_mr ['edae2b21'] (scan num: 73)
LivePlot did not get any data that corresponds to the x axis. m_stage_r
LivePlot did not get any data that corresponds to the y axis. I0_USAXS
                                                                                                                                                                              
I Tue-11:46:24 - PeakStats
================ =================
key              result           
================ =================
x                m_stage_r        
y                I0_USAXS         
cen              None             
com              None             
fwhm             None             
min              None             
max              None             
crossings        None             
tune_ok          False            
center           9.05830323225042 
initial_position 9.058302999999999
final_position   9.058302999999999
================ =================

                                                                                                                                                                              
I Tue-11:46:24 - PeakStats : no max reported
I Tue-11:46:24 - axis: m_stage_r
I Tue-11:46:24 - starting position: 9.058302999999999
I Tue-11:46:24 - peak detected: False
I Tue-11:46:24 - final position: 9.058302999999999
 




late ar tune example:

I Tue-11:57:57 - tuning axis: a_stage_r
                                                                                                                                                                              
D Tue-11:57:57 - gain=10000.0  rate: 825720.0  max: 950000  converged=[True, True]
D Tue-11:57:57 - gain=10000000.0  rate: 390520.0  max: 950000  converged=[True, True, True, True]
D Tue-11:57:57 - gain=1000000000.0  rate: 1580.0  max: 950000  converged=[True, True, True, True, True, True]
D Tue-11:57:57 - converged: [True, True, True, True, True, True]
I Tue-11:57:57 - Tuning axis a_stage_r, current position is 8.7477005

Transient Scan ID: 81     Time: 2020-09-15 11:57:57
Persistent Unique Scan ID: '29fef396-267d-4531-ad32-4fadab0ea1c5'
New stream: 'baseline'
New stream: 'aps_current_monitor'
New stream: 'primary'                                                                                                                                                         
+-----------+------------+------------+
|   seq_num |       time |   PD_USAXS |
+-----------+------------+------------+
|         1 | 11:57:58.9 |        268 |
|         2 | 11:57:59.3 |       1066 |                                                                                                                                       
|         3 | 11:57:59.7 |       3492 |                                                                                                                                       
|         4 | 11:58:00.2 |       7812 |                                                                                                                                       
|         5 | 11:58:00.6 |      13341 |                                                                                                                                       
|         6 | 11:58:01.0 |      19147 |                                                                                                                                       
|         7 | 11:58:01.4 |      24468 |                                                                                                                                       
|         8 | 11:58:01.8 |      30515 |                                                                                                                                       
|         9 | 11:58:02.3 |      36509 |                                                                                                                                       
|        10 | 11:58:02.7 |      42626 |                                                                                                                                       
|        11 | 11:58:03.1 |      48263 |                                                                                                                                       
|        12 | 11:58:03.5 |      53774 |                                                                                                                                       
|        13 | 11:58:03.9 |      59749 |                                                                                                                                       
|        14 | 11:58:04.3 |      65391 |                                                                                                                                       
|        15 | 11:58:04.8 |      71380 |                                                                                                                                       
|        16 | 11:58:05.2 |      77044 |                                                                                                                                       
|        17 | 11:58:05.6 |      81508 |                                                                                                                                       
|        18 | 11:58:06.0 |      83416 |                                                                                                                                       
|        19 | 11:58:06.5 |      83327 |                                                                                                                                       
|        20 | 11:58:06.9 |      80030 |                                                                                                                                       
|        21 | 11:58:07.3 |      75401 |                                                                                                                                       
|        22 | 11:58:07.7 |      69587 |                                                                                                                                       
|        23 | 11:58:08.1 |      63718 |                                                                                                                                       
|        24 | 11:58:08.6 |      57626 |                                                                                                                                       
|        25 | 11:58:09.0 |      52134 |                                                                                                                                       
|        26 | 11:58:09.4 |      46186 |                                                                                                                                       
|        27 | 11:58:09.8 |      40282 |                                                                                                                                       
|        28 | 11:58:10.2 |      34374 |                                                                                                                                       
|        29 | 11:58:10.6 |      28571 |                                                                                                                                       
|        30 | 11:58:11.0 |      22991 |                                                                                                                                       
|        31 | 11:58:11.5 |      17328 |                                                                                                                                       
|        32 | 11:58:11.9 |      11494 |                                                                                                                                       
|        33 | 11:58:12.3 |       6563 |                                                                                                                                       
|        34 | 11:58:12.7 |       3070 |                                                                                                                                       
|        35 | 11:58:13.1 |       1157 |                                                                                                                                       
I Tue-11:58:13 - PeakStats : no max reported
+-----------+------------+------------+
generator tune_ar ['29fef396'] (scan num: 81)
LivePlot did not get any data that corresponds to the x axis. a_stage_r
LivePlot did not get any data that corresponds to the y axis. PD_USAXS
                                                                                                                                                                              
I Tue-11:58:13 - PeakStats
================ =================
key              result           
================ =================
x                a_stage_r        
y                PD_USAXS         
cen              None             
com              None             
fwhm             None             
min              None             
max              None             
crossings        None             
tune_ok          False            
center           8.747700554073973
initial_position 8.7477005        
final_position   8.7477005        
================ =================

                                                                                                                                                                              
I Tue-11:58:14 - PeakStats : no max reported
I Tue-11:58:14 - axis: a_stage_r
I Tue-11:58:14 - starting position: 8.7477005
I Tue-11:58:14 - peak detected: False
I Tue-11:58:14 - final position: 8.7477005
                                                                                                                                                                              
I Tue-11:58:15 - tuning axis: a_stage_r2p
                                                                                                                                                                              
D Tue-11:58:15 - gain=10000.0  rate: 840480.0  max: 950000  converged=[True, True]
D Tue-11:58:15 - gain=10000000.0  rate: 392480.0  max: 950000  converged=[True, True, True, True]
D Tue-11:58:15 - gain=1000000000.0  rate: 1580.0  max: 950000  converged=[True, True, True, True, True, True]
D Tue-11:58:15 - converged: [True, True, True, True, True, True]
I Tue-11:58:15 - Tuning axis a_stage_r2p, current position is 43.5362



I Tue-12:33:08 - Tuning axis a_stage_r, current position is 8.7477005

Transient Scan ID: 106     Time: 2020-09-15 12:33:08
Persistent Unique Scan ID: '7937b0b4-959b-4fac-8fe3-498349d8ecdd'
New stream: 'baseline'
New stream: 'aps_current_monitor'
New stream: 'primary'                                                                                                                                                         
+-----------+------------+------------+
|   seq_num |       time |   PD_USAXS |
+-----------+------------+------------+
|         1 | 12:33:09.4 |        474 |
|         2 | 12:33:09.8 |       2483 |                                                                                                                                       
|         3 | 12:33:10.2 |       6760 |                                                                                                                                       
|         4 | 12:33:10.7 |      12497 |                                                                                                                                       
|         5 | 12:33:11.1 |      17886 |                                                                                                                                       
|         6 | 12:33:11.5 |      23548 |                                                                                                                                       
|         7 | 12:33:11.9 |      29227 |                                                                                                                                       
|         8 | 12:33:12.3 |      35077 |                                                                                                                                       
|         9 | 12:33:12.7 |      40941 |                                                                                                                                       
|        10 | 12:33:13.0 |      46653 |
|        11 | 12:33:13.4 |      52472 |                                                                                                                                       
|        12 | 12:33:13.9 |      58596 |                                                                                                                                       
|        13 | 12:33:14.3 |      64304 |                                                                                                                                       
|        14 | 12:33:14.7 |      70243 |                                                                                                                                       
|        15 | 12:33:15.1 |      76348 |                                                                                                                                       
|        16 | 12:33:15.5 |      81099 |                                                                                                                                       
|        17 | 12:33:15.8 |      83755 |
|        18 | 12:33:16.2 |      84224 |                                                                                                                                       
|        19 | 12:33:16.7 |      82124 |                                                                                                                                       
|        20 | 12:33:17.1 |      78662 |                                                                                                                                       
|        21 | 12:33:17.5 |      73193 |                                                                                                                                       
|        22 | 12:33:17.9 |      67240 |                                                                                                                                       
|        23 | 12:33:18.2 |      61913 |
|        24 | 12:33:18.6 |      56241 |                                                                                                                                       
|        25 | 12:33:19.1 |      50531 |                                                                                                                                       
|        26 | 12:33:19.5 |      44873 |                                                                                                                                       
|        27 | 12:33:19.9 |      39078 |                                                                                                                                       
|        28 | 12:33:20.3 |      33283 |                                                                                                                                       
|        29 | 12:33:20.7 |      27713 |                                                                                                                                       
|        30 | 12:33:21.1 |      22033 |                                                                                                                                       
|        31 | 12:33:21.4 |      16434 |
|        32 | 12:33:21.8 |      11126 |                                                                                                                                       
|        33 | 12:33:22.3 |       6027 |                                                                                                                                       
|        34 | 12:33:22.7 |       2908 |                                                                                                                                       
|        35 | 12:33:23.1 |        983 |                                                                                                                                       
I Tue-12:33:23 - PeakStats : no max reported
+-----------+------------+------------+
generator tune_ar ['7937b0b4'] (scan num: 106)
LivePlot did not get any data that corresponds to the x axis. a_stage_r
LivePlot did not get any data that corresponds to the y axis. PD_USAXS
                                                                                                                                                                              
I Tue-12:33:23 - PeakStats
================ =================
key              result           
================ =================
x                a_stage_r        
y                PD_USAXS         
cen              None             
com              None             
fwhm             None             
min              None             
max              None             
crossings        None             
tune_ok          False            
center           8.747700554073973
initial_position 8.7477005        
final_position   8.7477005        
================ =================

                                                                                                                                                                              
I Tue-12:33:24 - PeakStats : no max reported
I Tue-12:33:24 - axis: a_stage_r
I Tue-12:33:24 - starting position: 8.7477005
I Tue-12:33:24 - peak detected: False
I Tue-12:33:24 - final position: 8.7477005
```
